2018-07-04 16:59:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.osmc fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/jsonrpc_async/jsonrpc.py", line 29, in send_message
    response = yield from self._request(data=message.serialize())
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client.py", line 333, in _request
    await resp.start(conn, read_until_eof)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 766, in start
    self._continue = None
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/kodi.py", line 445, in async_update
    ['volume', 'muted']
  File "/srv/homeassistant/lib/python3.5/site-packages/jsonrpc_async/jsonrpc.py", line 31, in send_message
    raise TransportError('Transport Error', message, exc)
jsonrpc_base.jsonrpc.TransportError: ("Error calling method 'Application.GetProperties': Transport Error", TimeoutError())
