2018-06-03 00:05:23 ERROR (Thread-13) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 00:05:23 ERROR (Thread-13) [xiaomi_gateway] No data in response from hub None
2018-06-03 03:06:40 ERROR (Thread-16) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 03:06:40 ERROR (Thread-16) [xiaomi_gateway] No data in response from hub None
2018-06-03 12:20:46 ERROR (Thread-9) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 12:20:46 ERROR (Thread-9) [xiaomi_gateway] No data in response from hub None
2018-06-03 12:26:27 ERROR (Thread-21) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 12:26:27 ERROR (Thread-21) [xiaomi_gateway] No data in response from hub None
2018-06-03 13:28:26 ERROR (Thread-19) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 13:28:26 ERROR (Thread-19) [xiaomi_gateway] No data in response from hub None
2018-06-03 14:10:49 ERROR (Thread-10) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 14:10:49 ERROR (Thread-10) [xiaomi_gateway] No data in response from hub None
2018-06-03 16:33:46 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Cannot connect to host api.telegram.org:443 ssl:True [Temporary failure in name resolution]
2018-06-03 16:33:49 ERROR (MainThread) [homeassistant.components.light.hue] Unable to reach bridge 192.168.2.52
2018-06-03 16:33:50 ERROR (Thread-7) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 16:33:50 ERROR (Thread-7) [xiaomi_gateway] No data in response from hub None
2018-06-03 16:33:50 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.door_window_sensor_158d000200a8cd fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/binary_sensor/xiaomi_aqara.py", line 90, in update
    self._get_from_hub(self._sid)
  File "/srv/homeassistant/lib/python3.5/site-packages/xiaomi_gateway/__init__.py", line 362, in get_from_hub
    resp = self._send_cmd(cmd, "read_ack") if int(self.proto[0:1]) == 1 else self._send_cmd(cmd, "read_rsp")
  File "/srv/homeassistant/lib/python3.5/site-packages/xiaomi_gateway/__init__.py", line 295, in _send_cmd
    self._socket.sendto(cmd.encode(), (self.ip_adress, self.port))
OSError: [Errno 101] Network is unreachable
2018-06-03 17:51:49 ERROR (Thread-6) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 17:51:49 ERROR (Thread-6) [xiaomi_gateway] No data in response from hub None
2018-06-03 17:52:20 ERROR (Thread-5) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 17:52:20 ERROR (Thread-5) [xiaomi_gateway] No data in response from hub None
2018-06-03 17:56:16 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Cannot connect to host api.telegram.org:443 ssl:True [Temporary failure in name resolution]
2018-06-03 17:56:28 ERROR (Thread-4) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 17:56:28 ERROR (Thread-4) [xiaomi_gateway] No data in response from hub None
2018-06-03 18:14:26 ERROR (MainThread) [homeassistant.components.sensor.template] Could not render template Xiaomi Entrance Motion Sensor: UndefinedError: 'mappingproxy object' has no attribute 'battery_level'
2018-06-03 18:18:27 ERROR (MainThread) [homeassistant.components.sensor.template] Could not render template Xiaomi Button 1: UndefinedError: 'mappingproxy object' has no attribute 'battery_level'
2018-06-03 18:42:24 ERROR (MainThread) [homeassistant.components.sensor.template] Could not render template Xiaomi Main Door Sensor: UndefinedError: 'mappingproxy object' has no attribute 'battery_level'
2018-06-03 18:54:43 ERROR (MainThread) [homeassistant.components.sensor.template] Could not render template Xiaomi Basement Motion Sensor: UndefinedError: 'mappingproxy object' has no attribute 'battery_level'
2018-06-03 18:55:16 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `ssh pi@homeserver sudo systemctl restart home-assistant@homeassistant`, return code: -15
NoneType: None
2018-06-03 21:48:39 ERROR (Thread-10) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 21:48:39 ERROR (Thread-10) [xiaomi_gateway] No data in response from hub None
2018-06-03 22:03:07 ERROR (Thread-18) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 22:03:07 ERROR (Thread-18) [xiaomi_gateway] No data in response from hub None
2018-06-03 23:00:27 ERROR (Thread-17) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 23:00:27 ERROR (Thread-17) [xiaomi_gateway] No data in response from hub None
2018-06-03 23:10:16 ERROR (Thread-17) [xiaomi_gateway] Cannot connect to Gateway
2018-06-03 23:10:16 ERROR (Thread-17) [xiaomi_gateway] No data in response from hub None
